services:
  webp-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webp-converter-90s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webpconverter.rule=Host(`webp.barazi.cloud`)"
      - "traefik.http.routers.webpconverter.entrypoints=websecure"
      - "traefik.http.routers.webpconverter.tls=true"
      - "traefik.http.routers.webpconverter.tls.certresolver=letsencrypt"
      - "traefik.http.services.webpconverter.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: proxy
