services:
  webp-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webp-converter-90s
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - webp-converter-net

networks:
  webp-converter-net:
    driver: bridge
